### ISSUE TITLE
install package

### ISSUE THREAD

**Issue by Globegitter** [mikermcneil/machinepack-npm#1]
It would be great to have a `installPackage` function which can be used to locally install a downloaded package for a project, similar how `npm` itself has `npm.commands.install`.

**Comment by mikermcneil** [comment]
@Globegitter Ah totally- would be pretty easy to add if we required [`enpeem`](http://github.com/mikermcneil/enpeem)\- want to take a pass at it?

Basically the machine would take a `dir` input, `path.resolve()` it to make sure it's an absolute path, then use that as the target for npm install.  Then in its fn:

``` js
npm.install({
  dependencies: [
    'sails@0.10.1',
    'sails-disk@git://github.com/balderdashy/sails-disk.git#associations',
    'lodash'
  ]
  loglevel: 'silent',
  'cache-min': 999999999
}, function (err) { /* ... */ });
```

enpeem supports `npm update` as well, so we pretty trivially  add a machine for that too.

Only problem is that enpeem doesn't currently support specifying a different cwd.  using `process.chdir()` works but its super brittle, so i'd rather avoid it.  Do you know of an easy way to spin up a child process with its cwd set to a specific path?  Better yet, we could do something like [this](http://stackoverflow.com/a/14469516/486547) and have enpeem pass the target directory directly to npm:

``` js
mkdir -p ./install/here/node_modules
npm install --prefix ./install/here <package>
```

> disclaimer: I didn't test that code ^^  just copied and pasted from SO

(btw the reason I'm not just requiring `npm` programmatically in enpeem is that it means you have to actually reinstall `npm` in your node_modules, which is huge and slow)

**Comment by Globegitter** [comment]
Awesome, yeah I am on it.

**Comment by Globegitter** [comment]
Aahh yeah, just read through everything you said with specifying the path. That is a very good point.

**Comment by mikermcneil** [comment]
k just published a minor release w/ the code from your pr: https://www.npmjs.com/package/machinepack-npm
